### ISSUE TITLE
QMK-specific hex format

### ISSUE THREAD

**Issue by ItsHarper** [NoahAndrews/qmk_firmware#20]
We need to think about where the options for it get decided. Some will be decided by the keyboard, others by the hardware revision. I don't think any should be determined by the keymap, ideally.

For the Planck, I think it makes sense to create a promicro revision and a Teensy revision, for handwired versions of the boards.

We should be more careful about vetting submitted keymaps. The keymaps should never change hardware options that will affect the kshex.

**Comment by ItsHarper** [comment]
Zip the hex along with an info file.

**Comment by ItsHarper** [comment]
[qmk format conversation.pdf](https://github.com/NoahAndrews/qmk_firmware/files/765821/qmk.format.conversation.pdf)

**Comment by ItsHarper** [comment]
We may also want the ability to specify options in the make command.

**Comment by jackhumbert** [comment]
https://github.com/qmk/qmk_firmware/pull/1084 :)
